### ISSUE TITLE
gflags compilation problems

### ISSUE THREAD

**Issue by WangWenda98** [XikunLiu-huskit/GLIO#10]
Thank you very much for the excellent work of the author. Unfortunately, there was a problem that the gflags compilation did not pass during the compilation process. Do you have any good suggestions to solve it

CMake Error at /usr/lib/x86_64-linux-gnu/cmake/gflags/gflags-targets. cmake:37 (message):
Some (but not all) targets in this export set were already defined.

Targets Defined: gflags_shared; gflags_nothreads_shared

Targets not yet defined: gflags_static; gflags_nothreads_static

**Comment by WangWenda98** [comment]
Have been solved

**Comment by XikunLiu-huskit** [comment]
Hi @WangWenda98, great to know that!
