### ISSUE TITLE
Error from GTSAM when run the code

### ISSUE THREAD

**Issue by weisongwen** [XikunLiu-huskit/GLIO#14]
when run the ```roslaunch GLIO run_urban_hk.launch```
home/wws/GLIO_ws/devel/lib/GLIO/Estimator: symbol lookup error: /home/wws/GLIO_ws/devel/lib/GLIO/Estimator: undefined symbol: _ZNK5gtsam16NoiseModelFactor5printERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN5boost8functionIFS6_mEEE

Should be some error from the mismatch of the GTSAM path? Thanks.,

**Comment by XikunLiu-huskit** [comment]
Hi Dr. Wen, thanks to [printeger](https://printeger.github.io/)'s suggestion, I believe the problem can be solved by eliminating the previous installation for GTSAM and re-installing it through the recommended way:

```bash
sudo add-apt-repository ppa:borglab/gtsam-release-4.0
sudo apt install libgtsam-dev libgtsam-unstable-dev
```
