### ISSUE TITLE
How to get EmpFile(hksc141g.nav)?

### ISSUE THREAD

**Issue by Eric-Zhao1** [XikunLiu-huskit/GLIO#3]
Thanks for the excellent work! Can you explain what EmpFile means and How to get the EmpFile(hksc141g.nav)?
I can download roverMeasureFile from https://github.com/IPNL-POLYU/UrbanNavDataset#urbannav-hk-deep-urban-1,and baseMeasureFile from https://www.geodetic.gov.hk/en/rinex/downv.aspx. But I can't find EmpFile.
Looking forward to your reply!
thanks!

**Comment by XikunLiu-huskit** [comment]
Hi @Eric-Zhao1, thank you for your interest. The EmpFile stands for ephemeris file. You can download broadcast ephemeris either from [SMO](https://www.geodetic.gov.hk/en/rinex/downv.aspx) or from [NASA website](https://cddis.nasa.gov/archive/gnss/data/daily/) and convert it into .nav file through RTKCONV from RTKLIB. Feel free to reach out if you have further questions.

Best,
Xikun

**Comment by Garfield-cn** [comment]
Hi, thanks for your work. We also encounter this problem. As we know, RTKCONV can only convert one .21n or .21g into .nav, and it does not support multiple inputs. So how to generate one .nav file that contains all constellations? Thank you.
