### ISSUE TITLE
error when using docker

### ISSUE THREAD

**Issue by Joanna-HE** [XikunLiu-huskit/GLIO#4]
Thanks for such a good work! I want to use glio on ubuntu20.04 with ros noetic. The Novatel-msgs does not support the noetic, so I try to use docker. However, after make build, and when I try "sudo ./start_glio", the following error takes place: 

Error response from daemon: could not select device driver "" with capabilities: [[gpu]]
Error: failed to start containers: glio
Error response from daemon: Container e3b504b6ff6f0569b91c24ed4f3dae54f337ebc3cf48526319b2f58fdf9b5fc4 is not running

I am wondering how to solve this? Hope to hear from you.

**Comment by XikunLiu-huskit** [comment]
Hi @Joanna-HE, I guess your device is without an NV GPU. You may try to remove the `-e NVIDIA_DRIVER_CAPABILITIES="all"` and `--gpus all` in /start_glio.sh to see if you can run GLIO with your iGPU. Let me know if it helps:)

**Comment by Joanna-HE** [comment]
My device does not have a GPU, can I run glio with CPU?

**Comment by Joanna-HE** [comment]
I have tried to remove the -e NVIDIA_DRIVER_CAPABILITIES="all" and --gpus all in /start_glio.sh, the same error shows up again.

**Comment by Joanna-HE** [comment]
I also try "sudo ./start_glio" on a computer with NV GPU, the same error shows up. I am still wondering how to solve this. Hope to hear from you~

**Comment by XikunLiu-huskit** [comment]
Hi @Joanna-HE, Did you try deleting the old container and restarting it with ./start_glio.sh?

**Comment by Yangchengshuai** [comment]
> Hi @Joanna-HE, I guess your device is without an NV GPU. You may try to remove the `-e NVIDIA_DRIVER_CAPABILITIES="all"` and `--gpus all` in /start_glio.sh to see if you can run GLIO with your iGPU. Let me know if it helps:)

solved by run :
sudo docker run -it  -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -e GDK_SCALE -e GDK_DPI_SCALE -v ./dataset:/root/dataset  --name glio_test docker_glio /bin/bash
