### ISSUE TITLE
转弯时出现明显的地图漂移

### ISSUE THREAD

**Issue by Wppsdu** [XikunLiu-huskit/GLIO#5]
首先十分感谢您开源的GLIO，这是一个出色的大作！！
我们现在使用GLIO处理自己的数据时，在转弯的时间出现了地图漂移的问题，我们截取了一段视频放到附件中了
我们的lidar数据是16线的，imu数据是200hz，采集数据时初始时刻车头向西放置（但当时采集数据时没有记录准确的初始角Euler_r,Euler_p,Euler_y）。
现在我能想到关于旋转时地图出现明显漂移的有以下几个方面：
1:配置文件中初始化部分的设置不对（这个我们尝试修改，但仍然存在漂移现象，是否是不精确的初始化导致的）
2：我们的数据是16线的，GLIO处理的开源数据是32线的，但是GLIO中只使用到了平面点，角点没有使用，是否是这部分的差异导致地图转弯时发散  
3：转弯过快（网上的回答），这批数据我们使用LIO-SAM跑时没出现这个问题。

希望收到您的回复，
谢谢！！

https://github.com/XikunLiu-huskit/GLIO/assets/165349373/ce5dae64-e885-402f-8e10-582640156bbc

**Comment by HuL0713** [comment]
你好，我想问下你跑通demo了吗，为什么我跑TST数据，它就只显示一帧就不动了
