### ISSUE TITLE
it doesn't work, and there is no error

### ISSUE THREAD

**Issue by HuL0713** [XikunLiu-huskit/GLIO#7]
https://github.com/XikunLiu-huskit/GLIO/assets/126376188/49635b38-de62-4afd-823c-567f607ca1b2

**Comment by HuL0713** [comment]
looking forward to your reply, thank you!

**Comment by XikunLiu-huskit** [comment]
Hi @HuL0713 , looks like there is no gnss result. Can you check whether ''rtk_ini_path" publishes data?

**Comment by HuL0713** [comment]
Thanks for the reply, I've fixed this issue！

**Comment by zblamy** [comment]
Hi Hul0713, I've also encountered this problem. Could u pls tell me how u solved? My rtk_ini_path is also empty with ROS warning "waiting for station gnss message". Thank you!
